### ISSUE TITLE
Limit on number of training points?

### ISSUE THREAD

**Issue by asoyemi1** [kjappelbaum/gptchem#2]
Hello,

I recently downloaded your code after reading your paper. I was testing the model for melting point prediction and I observed the model would fail to make predictions when I went above 1000 training points (for example 2000 or 3000 training points). Is there a fundamental limit on how much data should be used for fine-tuning?

**Comment by kjappelbaum** [comment]
>I recently downloaded your code after reading your paper. I was testing the model for melting point prediction and I observed the model would fail to make predictions when I went above 1000 training points (for example 2000 or 3000 training points). Is there a fundamental limit on how much data should be used for fine-tuning?

Interesting observation about which I would like to learn more. Could you explain more about your setup? Did you fine tune? Which base model? Which dataset do you use? What task do you look at and how do you evaluate?

**Comment by asoyemi1** [comment]
I made small modifications to your run_experiments.py script (for lipophilicity) to predict the melting point of molecules (regression task) in an internal dataset. The dataset contained two columns for the SMILES and experimental melting points. I made use of the ada base model and fine tuned for 20 epochs. Apart from these no other settings in the script were changed.

**Comment by kjappelbaum** [comment]
Thanks for the details, can you perhaps first debug with a classification setting? I guess you cannot share the dataset with us for debugging (we can also do it via email)?

**Comment by asoyemi1** [comment]
I ran a further test, and it appears the issue might be the number of epochs and not the number of training points. So it fails when I try fine -tuning for 20 epoch with training set size 2000, however, it works as usual when n_epochs=8.

**Comment by kjappelbaum** [comment]
This makes sense. We are currently doing a more careful analysis of those hyper parameters and learning for too long gives a kind of overfitting

**Comment by asoyemi1** [comment]
Thanks for your responses!

**Comment by kjappelbaum** [comment]
Is it OK if I close this issue? Please let me know if there are any updates on your project or if there is anything I can do!

**Comment by asoyemi1** [comment]
It is okay to close. Thank you!
